### ISSUE TITLE
Wildfire Camera link appear in public facing map when point is added?

### ISSUE THREAD

**Issue by afackler** [afackler/FireEyes#2]
Is their some way (maybe using arcade) to add the URL for any wildfire cameras that may cover a fire point?

**Comment by afackler** [comment]
This could be a possibility, however I think that it should be done by hand as some points may have several cameras but not all of them can see the fire and I don't want to be adding misleading information on the points if you cannot view the fire on the cameras. My advice: if you see the smoke on the camera, put the URL in the comments.

**Comment by pjdohertygis** [comment]
This would be really tricky to do and only would work in California / Nevada. I suggest sticking with the manual method for now.
