### ISSUE TITLE
Survey - Add County and State Field

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/FireEyes#32]
We should add a County field and a State Field - this will help with jurisdictional issues. 

We can use the Attribute Actions in Smart Editor to auto-populate this or the reverse geocoding in Survey123 (costs credits?). 

Here is an example where it would have helped to have the County 

https://twitter.com/barkflight/status/1293635684398374912

**Comment by afackler** [comment]
Attribute Actions appear to work for this case but from what I can tell might need the point to be moved slightly in order for them to populate the county and state, unless there's a button somewhere I'm missing (I didn't even know you could do things like this in the smart editor)
