### ISSUE TITLE
Update weather station symbology

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/FireEyes#35]
From Emily at Esri

Here you go:
 
0 No Reading: https://www.arcgis.com/home/item.html?id=ed5a74b1ffa242e28594e0d582eed9e0
1 Light Breeze: https:// www.arcgis.com/home/item.html?id=b4cd385c93774b0e8283e272cc3988f8
2 Moderate Breeze: https:// www.arcgis.com/home/item.html?id=ffa65b7d20084c6bbfabef04bfde761a
3 Strong Breeze: https:// www.arcgis.com/home/item.html?id=b2cecc5cd0ed4223970bd771b6a74504
4 Gale Force: https:// www.arcgis.com/home/item.html?id=00287b40aaed4c39bb46580f713fe07e
5 Storm Force: https:// www.arcgis.com/home/item.html?id=ecff15b9a96e4a818f17e33f9373eb78
6 Hurricane Force: https:// www.arcgis.com/home/item.html?id=205a03f288d343e5acfa12f32a796d2d
 
I spent a TON of time customizing all of the popups and turning all the units into MPH and classifying by the Beaufort Scale.  You might also see the sky conditions field (weather station layer) has been split…that was a handy jam session with the wizard Paul Dodd. We split the field and then converted the text from KPH to MPH.
 
You may notice for the wind speed/gust forecasts…my approach was to make clear palette with only two colors (before it was a rainbow with multiple classes in KPH).  Now its just blue and pink in MPH each with a light, medium, and dark version.  Once you know that, you are able to quickly see the different wind categories and make that association easily.  Likewise for the station data…blue/purple with light, medium, dark.
 
Same for smoke…I had it with a gray palette, but I was not able to differentiate the classes.  I went with colors I sourced from photos I took of the Ferguson Fire sky behind my house a few years back…tan, yellow, and then a light, medium, and dark orange.
 
My approach is to make my maps as intuitive, clear, and beautiful as possible. 
 
Let me know if you need anything else!
 
EM

**Comment by afackler** [comment]
Okay these symbols have been updated accordingly and everything is looking great!

**Comment by pjdohertygis** [comment]
This looking great - wonder if we could add RH% to the label? Wind and relative humidity are the two key factors. It might be too much?

**Comment by afackler** [comment]
Well the function would be add a TextFormating.NewLine to make it look a bit more clean, however according to the information on that function, "Multi-line labels are NOT supported in the ArcGIS API 3.x for JavaScript nor in the ArcGIS Online map viewer." I added the RH next to the MPH for now but it can be take out if it's too much.
