### ISSUE TITLE
Clarify labeling of pop-ups by information source

### ISSUE THREAD

**Issue by rneppell** [afackler/FireEyes#5]
Suggest we update the display of pop-ups to clearly identify the source of their information to help users understand which reports are coming from our crowdsourced efforts and which are from IRWIN or other feeds. 

This is particularly relevant when we have both a crowdsourced point and an IRWIN point as when the user clicks on it, they'll get one pop-up with the "1 of 2" notation and can click through to the second one --- but it's not clearly labeled which is our crowdsourced vs which is from IRWIN. 

I'd suggest right after the fire name at the top of the pop-up adding " - IRWIN" or " - Crowdsourced" or something similar. 

Attaching screenshot of the Bighorn fire's pop-ups as example...

**Comment by rneppell** [comment]
![image](https://user-images.githubusercontent.com/44247905/83973314-67e96380-a89a-11ea-8984-3b4e9d16495e.png)

**Comment by rneppell** [comment]
![image](https://user-images.githubusercontent.com/44247905/83973326-7899d980-a89a-11ea-85ec-c1ce7a7d6da6.png)

**Comment by afackler** [comment]
I added the source in the title of the popup. Our Crowdsourced points now have "FireEyes Crowdsourced: [Firename] Fire" as the popup title, and Irwin simply has "IRWIN Fire Location" as the title. I'll give it some time to make sure this works before closing this out.

**Comment by rneppell** [comment]
Love it - looks great to me, thanks Adam!
