### ISSUE TITLE
Enhancement suggestion: filter by category from info summary sidebar?

### ISSUE THREAD

**Issue by rneppell** [afackler/FireEyes#6]
As we see days like today with a large number of fires, the map starts getting awfully crowded, so seems like anything we can do to give our public users easy ways to filter to the most relevant information for them would be a Good Thing. 

To that end: would it be possible to allow the user to turn on/off our crowdsourced fire reports based on their category as displayed in the Info Summary sidebar? It kinda *looks* like you should be able to (by which I mean from a user experience / UI perspective it intuitively seems to me like 'oh i bet i can click on this category to turn it on/off... oh, nope." ---  no idea what it would take make it work on backend).

So just now I was wishing I could go click, click and turn off the 12 Forward Progress Stopped and 15 Contained fires and just see the 13 Active, as an example...

![image](https://user-images.githubusercontent.com/44247905/84092225-999e1f80-a9ab-11ea-8b5e-03b741a6eca2.png)

**Comment by afackler** [comment]
I added in a filter option in the same group as the "turn on and off layers". If you think this belongs somewhere else, let me know

**Comment by rneppell** [comment]
Thanks Adam, this is cool and I think will definitely help the user experience. 

Minor suggested tweak: make the label for the filter "Active Fires Only" (vs just "Active Fires") to be clear that's what you get if you turn that filter on...
