### ISSUE TITLE
Minor enhancement: clear 'Unknown' from fire name field automatically

### ISSUE THREAD

**Issue by rneppell** [afackler/FireEyes#7]
For me at least (using Chrome on Windows 10) when I click on the 'Fire Name' field, the word "Unknown" is actually text in the field which I have to manually delete and then enter the actual name.  Ideal UE (imho) would be:

1. When form page loads users' cursor should automatically be on the Fire Name field
2a. If user begins typing 'Unknown' should disappear automatically, OR
2b. Maybe 'Unknown' doesn't appear at all (the field begins as blank) and if the user leaves it blank, the form automatically submits it with the name populated with the default 'Unknown'

![image](https://user-images.githubusercontent.com/44247905/84093895-5d20f280-a9b0-11ea-93a0-82d22849b067.png)

**Comment by afackler** [comment]
I made this blank and change the of the hint a bit. I don't think there is a way to automatically delete the Unknown.
