### ISSUE TITLE
Minor enhancement: Differentiate tab names

### ISSUE THREAD

**Issue by rneppell** [afackler/FireEyes#8]
Would it be possible to customize the name that gets displayed on browser tabs to be specific to the sub-section of the overall experience?

I've got the project homepage tab, the form submission page, and the public map open as three tabs in Chrome (on Win10) and they all are named 'Wildfire Initial Attack Experience', so it's hard to distinguish them. 

I do notice that the form has a green icon rather than the blue - if changing the text is hard but changing icons easy, different color/shape icons for each tab would do the trick too...

![image](https://user-images.githubusercontent.com/44247905/84094313-6eb6ca00-a9b1-11ea-93d5-077ceb9403de.png)

**Comment by afackler** [comment]
I don't think it's possible to change the tab name to match the page - It will only show the title of the experience itself.
